[feat] 차량 간단정보 구현
softeerbootcamp4th/Team6-AwesomeOrange-FE pull request #56
Opened 2024-07-31 09:45 UTC by darkdulgi

# #️⃣ 연관 이슈

- #8 

# 📝 작업 내용

> 차량의 간단한 정보를 보여줍니다. 차량 정보들은 처음엔 투명하다가 스크롤을 내려서 뷰포트가 차량 정보 섹션과 겹칠 시 애니메이션을 거쳐 나타납니다. 중간에 그래디언트로 하이라이트되는 부분 문자열이 있는데 그건 아직 미구현 상태입니다.

2024-07-31 14:14 UTC, lybell-art requested changes
src/simpleInformation/index.jsx 에 세미콜론 추가해주시면 머지해 드리겠습니다.

2024-07-31 14:14 UTC, lybell-art commented on src/simpleInformation/contentSection.jsx
> +              className={`${index % 2 ? style.highlightAnim : "text-neutral-800"} text-title-m whitespace-pre-wrap`}>
whitespace-pre-wrap은 json 데이터에서 \n을 대응하기 위해 사용하셨군요

2024-07-31 14:14 UTC, lybell-art commented on src/simpleInformation/contentSection.jsx
> +    const contentDOM = contentRef.current;
반복되는 부분을 별도의 변수로 떼신 것 아주 좋습니다.

2024-07-31 14:14 UTC, lybell-art commented on src/simpleInformation/contentSection.jsx
> +              key={index}
사실 key에 index를 쓰는 건 썩 좋은 습관은 아닙니다. 왜냐하면 index를 key로 쓴 상태에서 배열이 바뀌거나 하면 리액트에서 뭐가 제대로 삭제 안 되거나 하는 버그가 생길 수 있어요.
(리액트 내부에서 key를 지정 안 하면 index를 key로 쓰긴 합니다. 그러지 말라고 오류 뱉는 거지만요.)

자세한 건 다음 링크를 참조하세요. 
https://ko.react.dev/learn/rendering-lists#why-does-react-need-keys

2024-07-31 14:15 UTC, lybell-art commented on src/simpleInformation/index.jsx
> +  const contentList = JSONData.content
이거 왜 세미콜론이 없죠...?

2024-08-01 01:02 UTC, darkdulgi commented on src/simpleInformation/contentSection.jsx
> +    const contentDOM = contentRef.current;
https://velog.io/@cjhlsb/kencland

2024-08-01 01:18 UTC, lybell-art approved these changes

2024-08-01 01:18 UTC, lybell-art commented on src/simpleInformation/index.jsx
> +  const contentList = JSONData.content;
good

2024-08-01 01:18 UTC, merged